name: Lint Check

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js for editorconfig-checker
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Using a recent LTS version

      - name: Install editorconfig-checker
        run: npm install -g editorconfig-checker

      - name: Make scripts executable
        run: chmod +x ./scripts/lint.sh ./scripts/sync.sh

      - name: Run lint script
        run: ./scripts/lint.sh
