# This GitHub Actions workflow runs lint checks on every pull request to the main branch.
# It uses the fast, self-contained PowerShell script (.ps1) which runs cross-platform.

name: Lint Check

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PowerShell
        uses: actions/setup-powershell@v1
        with:
          # Use the latest stable version of PowerShell
          version: 'latest'

      - name: Run PowerShell Lint Script
        shell: pwsh
        run: |
          ./scripts/lint.ps1
