# This GitHub Actions workflow runs lint checks on every pull request to the main branch.
# This version is self-contained and does not require external dependencies to be installed.

name: Lint Check

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make scripts executable
        run: chmod +x ./scripts/lint.sh

      - name: Run lint script
        run: ./scripts/lint.sh